### ISSUE TITLE
data in the paper

### ISSUE THREAD

**Issue by WangZhenqing-RS** [links-ads/igarss-landslide-delineation#1]
Hello, the work in your papers is great, which gives me great inspiration and help. When can the data in the paper be public? Looking forward to your reply.

**Comment by Hassnain1** [comment]
Hello,
Your publication is interesting, could you please share the dataset used in the research here.
Thanks.

**Comment by PradeepYLN** [comment]
@tommonopolinks  Thank you for being willing to share your dataset with the public. Could you please share the dataset if possible?

**Comment by tommonopolinks** [comment]
@WangZhenqing-RS @Hassnain1 @PradeepYLN 
Source code and landslide inventories have now been uploaded to this repository.
I have not directly uploaded the S2 image dataset as it is very massive.
However, I included Jupyter Notebooks in the processing/ folder, which I have created and used to load each inventory, search relevant Sentinel-2 products and download them, and perform the rest of the preprocessing operations (cloud detection, DEM processing, S2 tiles generation), as detailed in the paper.
Please refer to the README to understand how to run the code.

Thank you for reaching out, and sorry for the late reply.

**Comment by joe-vettek** [comment]
@tommonopolinks Thank you very much for your sharing spirit, but I can't seem to run the data processing code well


```
Downloading products...
pre_s2: 100%|██████████| 12/12 [00:00<00:00, 12803.78it/s]
post_s2: 100%|██████████| 4/4 [00:00<?, ?it/s]
dem: 100%|██████████| 1/1 [00:00<?, ?it/s]
 25%|██▌       | 4/16 [00:00<00:00, 12.42it/s]
Traceback (most recent call last):
  File "E:\igarss-landslide-delineation\processing\colombia.py", line 236, in <module>
    mask = cloud_detector(stack)
  File "E:\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\igarss-landslide-delineation\src\cloud_detector.py", line 58, in forward
    assert set(self.bands).issubset(list(stack.long_name)), f"The given bands {list(stack.long_name)} do not contain the necessary bands for cloud masking. Please include bands {self.bands}."
AssertionError: The given bands ['s', 't', 'a', 'c', 'k', 's', 't', 'a', 'c', '-', 'c', '8', '2', '6', '8', '9', 'b', '6', 'b', '2', 'f', '0', '0', 'e', 'c', '4', '2', '9', '3', 'e', '8', '4', 'c', '2', 'f', 'a', 'a', 'b', '1', '0', '5', '2'] do not contain the necessary bands for cloud masking. Please include bands ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B8A', 'B09', 'B11', 'B12', 'AOT', 'WVP'].
```

**Comment by joe-vettek** [comment]
I noticed that the images I downloaded were completely black, but still tens to hundreds MB in size.

**Comment by joe-vettek** [comment]
Sorry, this is due to my bad network, and the downloaded file may be corrupted. Please note that the data is about 20-30G per folder, and the total may be 100G.

**Comment by indraraj493** [comment]
@joe-vettek  how can we resolve the issue which you are showing in this image.

**Comment by joe-vettek** [comment]
> @joe-vettek  how can we resolve the issue which you are showing in this image.
> 

i deleted the image which casue the crash and try download it again. i' think it's a network problem leading to a bad image file.

**Comment by indraraj493** [comment]
@joe-vettek  i am facing issue while trying to train bbunet model  precision, recall and f1-score all are coming 0 only. can you give suggestion how can i resolve this
<img width="981" alt="Screenshot 2024-10-09 at 4 51 04 PM" src="https://github.com/user-attachments/assets/c87da567-f6d8-4a78-b85a-fc217dcd5018">

**Comment by tommonopolinks** [comment]
The landslide inventory from Colombia is the smallest one and training only on the Japanese inventory may be a cause of overfitting. My advice would be to train on more landslide inventories at once and/or use another landslide inventory for validation, instead of the Colombian one.

**Comment by joe-vettek** [comment]
> @joe-vettek i am facing issue while trying to train bbunet model precision, recall and f1-score all are coming 0 only. can you give suggestion how can i resolve this我在尝试训练 bbunet 模型时遇到问题，精度、召回率和 f1 分数都仅为 0。你能给我建议吗我该如何解决这个问题 <img alt="Screenshot 2024-10-09 at 4 51 04 PM" width="981" src="https://private-user-images.githubusercontent.com/64495315/376143408-c87da567-f6d8-4a78-b85a-fc217dcd5018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTQyODgsIm5iZiI6MTcyODg5Mzk4OCwicGF0aCI6Ii82NDQ5NTMxNS8zNzYxNDM0MDgtYzg3ZGE1NjctZjZkOC00YTc4LWI4NWEtZmMyMTdkY2Q1MDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA4MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NWNiMjI3ZmY4NDAzNDM5NTE4ZjNhMjI4NzkyNDNjZGM3MTc2ZjE3MmIwYTYwMjAxNWYwMzFiYmU5MjYwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aV1pWf5OnRPZyejY6n8IDcHrp8c4IAompveNv3bvNCA">

strange, i use the china dataset emmm, maybe your dataset downloaded has some problem?

**Comment by indraraj493** [comment]
hello @joe-vettek , @tommonopolinks 
I am facing an issue related to CUDA out of memory (OOM) errors when attempting to download the Sentinel-2 (S2) inventory for Haiti, Indonesia, and China. The error occurs while executing the following lines of code:
<img width="853" alt="Screenshot 2024-10-15 at 4 39 45 PM" src="https://github.com/user-attachments/assets/66e1475c-f120-43df-9646-315c95b38108">

System Configuration:

GPUs: 4 x 16GB
Software environment: python version 3.10.12 

Despite having multiple GPUs with 16GB of memory each, the memory seems insufficient to handle the download process. It appears that the process exceeds the available GPU memory resources.

giving error like this 
<img width="1387" alt="Screenshot 2024-10-15 at 4 38 29 PM" src="https://github.com/user-attachments/assets/a28310f4-8b45-42f9-9bc3-c25f0344f51f">


Please give me any suggestions to reduce batch size or i can make some change in these code like do some for pre images first and after for post images.

thanks

**Comment by tommonopolinks** [comment]
Hi @indraraj493, I was not aware of how much GPU memory was needed for the cloud detection part, as I used a fairly big GPU (80GB) and had no problems.
The cloud detector used is a fully convolutional one, therefore a full-sized image can be fed into it without tiling needed. This obviously becomes a GPU memory bottleneck when an image is too large, and tiling the image beforehand will be needed. Perhaps I can modify code in src/cloud_detector.py to optionally perform this tiling. I will do it when I have time.

In the meanwhile, you could either try modifying the code yourself or simply rely on `device='cpu'` (if your RAM is sufficiently large)

**Comment by indraraj493** [comment]
thanks @tommonopolinks ,
the code is working fine on cpu.
I truly appreciate the effort you've put into developing this resource—it’s been really helpful in my work.

I’m reaching out to ask if you have any suggestions or ideas on how I might improve the current methodology. Specifically, I'm looking for ways to enhance [the method/model/approach], and I was wondering if you could offer any guidance or point me toward a particular model or technique that could complement the existing work.

Thank you for your time, and I look forward to any insights you might have!

**Comment by tommonopolinks** [comment]
Thank you @indraraj493, glad that you found my work useful!
Ways to enhance the model's performances would be:
- **Additional landslides in the training set (data quantity)**. Scanning the literature for other open-access landslide inventories, process them as done in this repo and adding them to the training set. I am currently pursuing this path, for a 2nd version of my BBUnet model.
- **Finding ways to deal with inaccurate ground-truth delineations (data quality)**. What I noticed is that some manually-annotated landslide inventories you can find online are not very accurate in terms of delineation accuracy. This is aggravated by Sentinel-2 relatively low spatial resolution of 10 m/px. One way to deal with not-so-accurate delineations could be to use label-smoothing techniques such as [SVLS](https://github.com/mobarakol/SVLS) or [GeoLS](https://github.com/adigasu/GeoLS).
- **Experiment with different and/or more aggressive data augmentation (data variety)**. You could try experimenting with mask-wise augmentations like mask erosion/dilation, or other augmentation techniques used specifically for satellite images, e.g. [MixChannel](https://www.mdpi.com/2072-4292/13/11/2181).

Also, experimenting with other change detection models and strategies to fuse DEM and S2 data might be a good idea.
