### ISSUE TITLE
getting issue in running code 

### ISSUE THREAD

**Issue by indraraj493** [links-ads/igarss-landslide-delineation#2]
Downloading products...
pre_s2: 100%|██████████| 12/12 [00:00<00:00, 12803.78it/s]
post_s2: 100%|██████████| 4/4 [00:00<?, ?it/s]
dem: 100%|██████████| 1/1 [00:00<?, ?it/s]
 25%|██▌       | 4/16 [00:00<00:00, 12.42it/s]
Traceback (most recent call last):
  File "E:\igarss-landslide-delineation\processing\colombia.py", line 236, in <module>
    mask = cloud_detector(stack)
  File "E:\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\igarss-landslide-delineation\src\cloud_detector.py", line 58, in forward
    assert set(self.bands).issubset(list(stack.long_name)), f"The given bands {list(stack.long_name)} do not contain the necessary bands for cloud masking. Please include bands {self.bands}."
AssertionError: The given bands ['s', 't', 'a', 'c', 'k', 's', 't', 'a', 'c', '-', 'c', '8', '2', '6', '8', '9', 'b', '6', 'b', '2', 'f', '0', '0', 'e', 'c', '4', '2', '9', '3', 'e', '8', '4', 'c', '2', 'f', 'a', 'a', 'b', '1', '0', '5', '2'] do not contain the necessary bands for cloud masking. Please include bands ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B8A', 'B09', 'B11', 'B12', 'AOT', 'WVP'].

**Comment by tommonopolinks** [comment]
Please refer to the [previous open issue](https://github.com/links-ads/igarss-landslide-delineation/issues/1#issuecomment-2389106351)

**Comment by indraraj493** [comment]
thanks resolved
