### ISSUE TITLE
getting issue while getting results of bbunet

### ISSUE THREAD

**Issue by indraraj493** [links-ads/igarss-landslide-delineation#3]
hi @tommonopolinks ,
First of all, I want to thank you for your amazing work on this project. The functionality and the code quality are really impressive, and I've found it incredibly helpful in my own work!

I am currently facing an issue while i am trying to train bbunet model here it is giving precision, recall and f1 score  zero . Here's a bit more detail:
i am trying to run this command 
python train.py --yaml="configs/bbunet.yaml"

i am attaching image as well for issue
<img width="981" alt="Screenshot 2024-10-09 at 4 51 04 PM" src="https://github.com/user-attachments/assets/15ee604d-410b-4160-964a-543c4c98b5c0">

Question:
Could you please guide me on how I might be able to resolve this? Any suggestions or pointers would be greatly appreciated.

Once again, thanks for all your hard work on this project, and I look forward to hearing your thoughts!

**Comment by tommonopolinks** [comment]
Please have a look at my answer in the [other issue](https://github.com/links-ads/igarss-landslide-delineation/issues/1#issuecomment-2410347146)

**Comment by indraraj493** [comment]
sure
